server:
  port: 8089

spring:
  application:
    name: favorite-service
  config:
    import:
      - optional:nacos:favorite-service.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jingdezhen_tourism?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:your-db-password}
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
    loadbalancer:
      enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jingdezhen.tourism.common.entity

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

